### ISSUE TITLE
not possible to install on Windows Platform

### ISSUE THREAD

**Issue by WagnerBeccard** [PArns/ioBroker.amazon-dash#12]
German system, so it is a correct fall =D 

`$ ./iobroker add amazon-dash
npm install iobroker.amazon-dash --production --prefix "C:/ioBroker" (System call)
Der Befehl "apt-get" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

Der Befehl "true" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

npm
 ERR! Windows_NT 6.3.9600npm
 ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "iobroker.amazon-dash" "--production" "--prefix" "C:/ioBroker"npm
 ERR! node v4.5.0npm ERR! npm  v2.15.9
npm ERR! code
 ELIFECYCLE
npm ERR! iobroker.amazon-dash@0.2.1 preinstall: `apt-get install libpcap-dev -y || true`
npm ERR! Exit status 1

npm ERR! npm ERR! Failed at the iobroker.amazon-dash@0.2.1 preinstall script 'apt-get install libpcap-dev -y || true'.

npm ERR! This is most likely a problem with the iobroker.amazon-dash package,npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!
     apt-get install libpcap-dev -y || truenpm ERR! You can get information on how to open an issue for this project with:
npm ERR!
     npm bugs iobroker.amazon-dashnpm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls iobroker.amazon-dash
npm 
ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:npm ERR!
     C:\ioBroker\node_modules\iobroker\npm-debug.log
host.john install adapter amazon-dash
npm install iobroker.amazon-dash --production --prefix "C:/ioBroker" (System call)
Der Befehl "apt-get" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

Der Befehl "true" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

npm
 ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "iobroker.amazon-dash" "--production" "--prefix" "C:/ioBroker"
npm ERR! node v4.5.0npm ERR! npm  v2.15.9

npm ERR! code ELIFECYCLE
npm ERR! iobroker.amazon-dash@0.2.1 preinstall: `apt-get install libpcap-dev -y || true`
npm ERR! Exit status 1

npm ERR! npm ERR! Failed at the iobroker.amazon-dash@0.2.1 preinstall script 'apt-get install libpcap-dev -y || true'.
npm ERR! This is most likely a problem with the iobroker.amazon-dash package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     apt-get install libpcap-dev -y || true
npm ERR! You can get information on how to open an issue for this project with:

npm ERR!     npm bugs iobroker.amazon-dashnpm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls iobroker.amazon-dash
npm ERR! There is likely additional logging output above.

npm ERR!
 Please include the following file with any support request:npm ERR!
     C:\ioBroker\node_modules\iobroker\npm-debug.log
host.john install adapter amazon-dash
npm install iobroker.amazon-dash --production --prefix "C:/ioBroker" (System call)
Der Befehl "apt-get" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

Der Befehl "true" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

npm
 ERR! Windows_NT 6.3.9600npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "iobroker.amazon-dash" "--production" "--prefix" "C:/ioBroker"

npm ERR! node v4.5.0npm ERR! npm  v2.15.9

npm
 ERR! code ELIFECYCLE
npm ERR! iobroker.amazon-dash@0.2.1 preinstall: `apt-get install libpcap-dev -y || true`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iobroker.amazon-dash@0.2.1 preinstall script 'apt-get install libpcap-dev -y || true'.
npm ERR! This is most likely a problem with the iobroker.amazon-dash package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     apt-get install libpcap-dev -y || true
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iobroker.amazon-dash
npm ERR! Or if that isn't available, you can get their info via:
npm
 ERR! npm ERR!     npm owner ls iobroker.amazon-dash
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:npm ERR!     C:\ioBroker\node_modules\iobroker\npm-debug.log

host.john install adapter amazon-dash
ERROR: host.john Cannot install amazon-dash
ERROR: process exited with code 13`

**Comment by PArns** [comment]
Sorry, this adapter is due to the libs linux only atm!

**Comment by WagnerBeccard** [comment]
Terefore i've got a brandnew Raspberry Pi.  
I think it is my fail.
But still 

```

$ ./iobroker add amazon-dash
npm install iobroker.amazon-dash --production --prefix "/opt/iobroker" (System call)
npm
 WARN lifecycle iobroker.amazon-dash@0.2.1~preinstall: cannot run in wd %s %s (wd=%s) iobroker.amazon-dash@0.2.1 apt-get install libpcap-dev -y || true /opt/iobroker/node_modules/.staging/iobroker.amazon-dash-eb5038e9
../socket_watcher.cpp: In static member function ‘static void SocketWatcher::New(const Nan::FunctionCallbackInfo<v8::Value>&)’:../socket_watcher.cpp:104:49: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is deprecated (declared at /root/.node-gyp/6.10.3/include/node/v8.h:3275): Use maybe version [-Wdeprecated-declarations]
     info.GetReturnValue().Set(cons->NewInstance());
                                                 ^

In file included from ../src/dns_sd.cpp:1:0:../src/mdns.hpp:32:20: fatal error: dns_sd.h: Datei oder Verzeichnis nicht gefunden
 #include <dns_sd.h>
                    ^
compilation terminated.

make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
gyp ERR! build error gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR!
 System Linux 4.9.28-v7+gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

gyp ERR! cwd /opt/iobroker/node_modules/mdns
gyp ERR! node -v v6.10.3gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

../pcap_binding.cc:2:23: fatal error: pcap/pcap.h: Datei oder Verzeichnis nicht gefunden #include <pcap/pcap.h>
                       ^
compilation terminated.

make: *** [Release/obj.target/pcap_binding/pcap_binding.o] Error 1
gyp
 
ERR!
 build error 
gyp ERR! stack Error: `make` failed with exit code: 2gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

gyp ERR! System Linux 4.9.28-v7+gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/pcap
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm
 WARN optional SKIPPING OPTIONAL DEPENDENCY: mdns@2.3.3 (node_modules/mdns):npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mdns@2.3.3 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! Linux 4.9.28-v7+npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "iobroker.amazon-dash" "--production" "--prefix" "/opt/iobroker"
npm ERR! node v6.10.3

npm ERR! npm  v3.10.10npm ERR! code ELIFECYCLE

npm ERR! pcap@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pcap@2.0.0 install script 'node-gyp rebuild'.
npm 
ERR! Make sure you have the latest version of node.js and npm installed.npm ERR! If you do, this is most likely a problem with the pcap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pcap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pcap

npm
 ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:npm ERR!
     /npm-debug.log
host.ioBroker-RasPi install adapter amazon-dash
npm install iobroker.amazon-dash --production --prefix "/opt/iobroker" (System call)
npm
 WARN lifecycle iobroker.amazon-dash@0.2.1~preinstall: cannot run in wd %s %s (wd=%s) iobroker.amazon-dash@0.2.1 apt-get install libpcap-dev -y || true /opt/iobroker/node_modules/.staging/iobroker.amazon-dash-eb5038e9
../socket_watcher.cpp: In static member function ‘static void SocketWatcher::New(const Nan::FunctionCallbackInfo<v8::Value>&)’:../socket_watcher.cpp:104:49: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is deprecated (declared at /root/.node-gyp/6.10.3/include/node/v8.h:3275): Use maybe version [-Wdeprecated-declarations]
     info.GetReturnValue().Set(cons->NewInstance());
                                                 ^

In file included from ../src/dns_sd.cpp:1:0:../src/mdns.hpp:32:20: fatal error: dns_sd.h: Datei oder Verzeichnis nicht gefunden
 #include <dns_sd.h>
                    ^

compilation terminated.
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
gyp
 ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

gyp ERR! System Linux 4.9.28-v7+gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/mdns
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

../pcap_binding.cc:2:23: fatal error: pcap/pcap.h: Datei oder Verzeichnis nicht gefunden #include <pcap/pcap.h>
                       ^
compilation terminated.

make: *** [Release/obj.target/pcap_binding/pcap_binding.o] Error 1
gyp
 ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

gyp ERR! System Linux 4.9.28-v7+gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/pcap
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mdns@2.3.3 (node_modules/mdns):npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mdns@2.3.3 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! Linux 4.9.28-v7+npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "iobroker.amazon-dash" "--production" "--prefix" "/opt/iobroker"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! pcap@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pcap@2.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pcap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pcap

npm ERR! Or if that isn't available, you can get their info via:npm ERR!     npm owner ls pcap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
     /npm-debug.log
host.ioBroker-RasPi install adapter amazon-dash
npm install iobroker.amazon-dash --production --prefix "/opt/iobroker" (System call)
npm
 
WARN
 
lifecycle
 iobroker.amazon-dash@0.2.1~preinstall: cannot run in wd %s %s (wd=%s) iobroker.amazon-dash@0.2.1 apt-get install libpcap-dev -y || true /opt/iobroker/node_modules/.staging/iobroker.amazon-dash-eb5038e9
../socket_watcher.cpp: In static member function ‘static void SocketWatcher::New(const Nan::FunctionCallbackInfo<v8::Value>&)’:../socket_watcher.cpp:104:49: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is deprecated (declared at /root/.node-gyp/6.10.3/include/node/v8.h:3275): Use maybe version [-Wdeprecated-declarations]
     info.GetReturnValue().Set(cons->NewInstance());
                                                 ^

In file included from ../src/dns_sd.cpp:1:0:../src/mdns.hpp:32:20: fatal error: dns_sd.h: Datei oder Verzeichnis nicht gefunden
 #include <dns_sd.h>
                    ^
compilation terminated.

make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
gyp
 ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

gyp ERR! System Linux 4.9.28-v7+gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/mdns
gyp ERR! node -v v6.10.3

gyp ERR! node-gyp -v v3.4.0gyp ERR! not ok 

../pcap_binding.cc:2:23: fatal error: pcap/pcap.h: Datei oder Verzeichnis nicht gefunden #include <pcap/pcap.h>
                       ^
compilation terminated.

make: *** [Release/obj.target/pcap_binding/pcap_binding.o] Error 1
gyp
 ERR! build error 
gyp
 ERR! stack Error: `make` failed with exit code: 2gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

gyp ERR! System Linux 4.9.28-v7+gyp
 ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"gyp ERR! cwd /opt/iobroker/node_modules/pcap
gyp ERR! node -v v6.10.3

gyp ERR! node-gyp -v v3.4.0gyp ERR! not ok 

npm
 WARN optional SKIPPING OPTIONAL DEPENDENCY: mdns@2.3.3 (node_modules/mdns):npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mdns@2.3.3 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm
 ERR! Linux 4.9.28-v7+npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "iobroker.amazon-dash" "--production" "--prefix" "/opt/iobroker"
npm ERR! 
node v6.10.3npm ERR! npm  v3.10.10

npm ERR! code ELIFECYCLE
npm ERR! pcap@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pcap@2.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pcap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pcap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pcap
npm 
ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:npm ERR!
     /npm-debug.log
host.ioBroker-RasPi install adapter amazon-dash
ERROR: host.ioBroker-RasPi Cannot install amazon-dash
ERROR: process exited with code 13
```
