### ISSUE TITLE
Adapter is not working anymore on Orange pi

### ISSUE THREAD

**Issue by MegaMatze** [PArns/ioBroker.amazon-dash#38]
Hi,

unfortunately after switching from Raspberry to Orange Pi running Armbian, the Amazon Dash Button Adapter in ioBroker ist no longer functioning properly. Status stays red and does not change to green. libpcap-dev has been installed, removed and then installed again but no change unfortunately. Log below, is this a know issue?

2018-07-02 17:32:49.574  - [31merror[39m: Caught by controller[0]: Error: Module version mismatch. Expected 48, got 64.
2018-07-02 17:32:49.575  - [31merror[39m: Caught by controller[0]:     at Error (native)
2018-07-02 17:32:49.576  - [31merror[39m: Caught by controller[0]:     at Object.Module._extensions..node (module.js:604:18)
2018-07-02 17:32:49.577  - [31merror[39m: Caught by controller[0]:     at Module.load (module.js:494:32)
2018-07-02 17:32:49.577  - [31merror[39m: Caught by controller[0]:     at tryModuleLoad (module.js:453:12)
2018-07-02 17:32:49.578  - [31merror[39m: Caught by controller[0]:     at Function.Module._load (module.js:445:3)
2018-07-02 17:32:49.578  - [31merror[39m: Caught by controller[0]:     at Module.require (module.js:504:17)
2018-07-02 17:32:49.579  - [31merror[39m: Caught by controller[0]:     at require (internal/module.js:20:19)
2018-07-02 17:32:49.579  - [31merror[39m: Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/pcap/pcap.js:3:21)
2018-07-02 17:32:49.580  - [31merror[39m: Caught by controller[0]:     at Module._compile (module.js:577:32)
2018-07-02 17:32:49.580  - [31merror[39m: Caught by controller[0]:     at Object.Module._extensions..js (module.js:586:10)
2018-07-02 17:32:49.581  - [31merror[39m: host.orangepiplus2e instance system.adapter.amazon-dash.0 terminated with code 0 (OK)
2018-07-02 17:32:49.582  - [32minfo[39m: host.orangepiplus2e Restart adapter system.adapter.amazon-dash.0 because enabled
2018-07-02 17:33:14.303  - [32minfo[39m: host.orangepiplus2e object change system.adapter.amazon-dash.0
2018-07-02 17:33:14.327  - [32minfo[39m: host.orangepiplus2e instance system.adapter.amazon-dash.0 started with pid 3182
2018-07-02 17:33:15.177  - [32minfo[39m: host.orangepiplus2e object change system.adapter.amazon-dash.0
2018-07-02 17:33:15.186  - [32minfo[39m: host.orangepiplus2e stopInstance system.adapter.amazon-dash.0
2018-07-02 17:33:15.187  - [32minfo[39m: host.orangepiplus2e stopInstance system.adapter.amazon-dash.0 killing pid 3182
2018-07-02 17:33:15.230  - [33mwarn[39m: host.orangepiplus2e instance system.adapter.amazon-dash.0 terminated due to SIGTERM
2018-07-02 17:33:15.233  - [32minfo[39m: host.orangepiplus2e instance system.adapter.amazon-dash.0 terminated with code null ()
2018-07-02 17:33:16.025  - [32minfo[39m: host.orangepiplus2e object change system.adapter.amazon-dash.0
2018-07-02 17:33:16.045  - [32minfo[39m: host.orangepiplus2e instance system.adapter.amazon-dash.0 started with pid 3192
2018-07-02 17:33:16.725  - [32minfo[39m: host.orangepiplus2e object change system.adapter.amazon-dash.0
2018-07-02 17:33:16.727  - [32minfo[39m: host.orangepiplus2e stopInstance system.adapter.amazon-dash.0
2018-07-02 17:33:16.728  - [32minfo[39m: host.orangepiplus2e stopInstance system.adapter.amazon-dash.0 killing pid 3192
2018-07-02 17:33:16.752  - [33mwarn[39m: host.orangepiplus2e instance system.adapter.amazon-dash.0 terminated due to SIGTERM
2018-07-02 17:33:16.753  - [32minfo[39m: host.orangepiplus2e instance system.adapter.amazon-dash.0 terminated with code null ()
2018-07-02 17:33:19.255  - [32minfo[39m: host.orangepiplus2e instance system.adapter.amazon-dash.0 started with pid 3202
2018-07-02 17:33:21.714  - [31merror[39m: amazon-dash.0 uncaught exception: Module version mismatch. Expected 48, got 64.
2018-07-02 17:33:21.737  - [31merror[39m: amazon-dash.0 Error: Module version mismatch. Expected 48, got 64.
    at Error (native)
    at Object.Module._extensions..node (module.js:604:18)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/iobroker/node_modules/pcap/pcap.js:3:21)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
2018-07-02 17:33:22.233  - [32minfo[39m: amazon-dash.0 starting. Version 0.2.9 in /opt/iobroker/node_modules/iobroker.amazon-dash, node: v6.14.3
2018-07-02 17:33:22.293  - [32minfo[39m: amazon-dash.0 terminating
2018-07-02 17:33:22.327  - [31merror[39m: Caught by controller[0]: Error: Module version mismatch. Expected 48, got 64.
2018-07-02 17:33:22.328  - [31merror[39m: Caught by controller[0]:     at Error (native)
2018-07-02 17:33:22.329  - [31merror[39m: Caught by controller[0]:     at Object.Module._extensions..node (module.js:604:18)
2018-07-02 17:33:22.329  - [31merror[39m: Caught by controller[0]:     at Module.load (module.js:494:32)
2018-07-02 17:33:22.330  - [31merror[39m: Caught by controller[0]:     at tryModuleLoad (module.js:453:12)
2018-07-02 17:33:22.330  - [31merror[39m: Caught by controller[0]:     at Function.Module._load (module.js:445:3)
2018-07-02 17:33:22.330  - [31merror[39m: Caught by controller[0]:     at Module.require (module.js:504:17)
2018-07-02 17:33:22.330  - [31merror[39m: Caught by controller[0]:     at require (internal/module.js:20:19)
2018-07-02 17:33:22.331  - [31merror[39m: Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/pcap/pcap.js:3:21)
2018-07-02 17:33:22.331  - [31merror[39m: Caught by controller[0]:     at Module._compile (module.js:577:32)
2018-07-02 17:33:22.331  - [31merror[39m: Caught by controller[0]:     at Object.Module._extensions..js (module.js:586:10)
2018-07-02 17:33:22.332  - [31merror[39m: host.orangepiplus2e instance system.adapter.amazon-dash.0 terminated with code 0 (OK)
2018-07-02 17:33:22.332  - [32minfo[39m: host.orangepiplus2e Restart adapter system.adapter.amazon-dash.0 because enabled

**Comment by PArns** [comment]
Please remove and reinstall the adapter or recompile via gyp rebuild.

You have upgraded your node version ... Therefore some libs needs to be recompiled

**Comment by MegaMatze** [comment]
hmmm the removal and reinstallation doesnt seem to be working. could you tell me how to recompile via gyp?

**Comment by PArns** [comment]
Ensure you've node-gyp up and running (`apt install node-gyp` on a debian)
Go to the iobroker.amazon-dash dir (`cd /opt/iobroker/node_modules/iobroker.amazon-dash/`) and type in `node-gyp rebuild`
