### ISSUE TITLE
Wählbarer Netzwerkeingang

### ISSUE THREAD

**Issue by StrayDog2205** [PArns/ioBroker.amazon-dash#49]
Ich musste bei mir aufgrund eines BOND Anschlusses den Interface nachträglich auf "ovs_bond0" legen.
Hintergrund ist der, das ich ioBroker über Docker auf einem NAS laufen habe, welches eine BOND anbindung hat.
Nach der Installation ist habe ich keinen DashButton einbinden können.
In der "main.js" ist mir aufgefallen, das an der stelle, wo im Code unten jetzt -"ovs_bond0"- steht vorher nur -""- stand.
Warunm dort nicht -"eth0"- stand, weiß ich leider nicht.

Mit der änderung geht es jetzt.

Praktisch wäre es, im Adapter ein Dropdown mit einigen gängigen Interfaces zu haben, wenn man doch mal abseits von eth0 bewegen sollte.

`    if (typeof adapter.config.interface == 'undefined' || adapter.config.interface === '') {
        adapter.config.interface = "ovs_bond0";
        adapter.log.info('starting pcap session on default interface');
    } else {
        adapter.log.info('starting pcap session on interface '+adapter.config.interface);
    }`

**Comment by hmersch** [comment]
Hallo 
Ich brauche das Feature auch: Ich habe Wireguard auf dem gleichen NUC laufen. 
Wenn der AmazonDash-ADapter startet und vorher das Wireguard Interface "up" ist, bekommt der DashAdapter nciht die entsprechenden Rechte auf diesem device:
`

host.RoofServer | 2020-10-03 13:21:42.121 | error | Caught by controller[0]: at Object.exports.createSession (/opt/iobroker/node_modules/iobroker.amazon-dash/node_modules/pcap/pcap.js:131:12)
-- | -- | -- | --
host.RoofServer | 2020-10-03 13:21:42.121 | error | Caught by controller[0]: at new PcapSession (/opt/iobroker/node_modules/iobroker.amazon-dash/node_modules/pcap/pcap.js:60:39)
host.RoofServer | 2020-10-03 13:21:42.121 | error | Caught by controller[0]: Error: expression rejects all packets

`

Wenn ich explizit per Config die Dash-Button-relevante  Netzwerkschnitte konfigurieren könnte, wäre das super. 

Gruss - Henning
