### ISSUE TITLE
Error: socket: Operation not permitted

### ISSUE THREAD

**Issue by Acer54** [PArns/ioBroker.amazon-dash#63]
After updating Raspbian today with following packages: (sudo apt dist-upgrade)
  base-files chromium-browser chromium-browser-l10n
  chromium-codecs-ffmpeg-extra gstreamer1.0-alsa gstreamer1.0-plugins-base
  gstreamer1.0-x java-common libasound2 libasound2-data libaudiofile1
  libbasicusageenvironment1 libgroupsock8 libgs9 libgs9-common
  libgstreamer-plugins-base1.0-0 libjs-jquery liblivemedia57 libobrender32v5
  libobt2v5 libpam-systemd libpng-dev libpng-tools libpng16-16
  libraspberrypi-bin libraspberrypi-dev libraspberrypi-doc libraspberrypi0
  libsmbclient libssh2-1 libsystemd0 libudev-dev libudev1 libusageenvironment3
  libwbclient0 lxplug-ejecter lxplug-network **nodejs** openbox pipanel
  python-cryptography python-six python3-cryptography python3-six
  raspberrypi-bootloader raspberrypi-kernel raspi-config
  raspi-copies-and-fills raspi-gpio rc-gui realvnc-vnc-server rpd-plym-splash
  rpi-chromium-mods rsync samba-common samba-libs systemd systemd-sysv tzdata
  udev unzip wget wiringpi

I have got the following Error-Messages in my Log (constantly repeating)

`info	Restart adapter system.adapter.amazon-dash.0 because enabled
error	instance system.adapter.amazon-dash.0 terminated with code 0 (OK)
error	Caught by controller[0]: at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:787:25)
error	Caught by controller[0]: at createInstancesObjects (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:748:13)
error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:788:29
error	Caught by controller[0]: at initAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4990:18)
error	Caught by controller[0]: at Adapter.emit (events.js:208:7)
error	Caught by controller[0]: at emitNone (events.js:106:13)
error	Caught by controller[0]: at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.amazon-dash/main.js:43:5)
error	Caught by controller[0]: at main (/opt/iobroker/node_modules/iobroker.amazon-dash/main.js:78:29)
error	Caught by controller[0]: at Object.exports.createSession (/opt/iobroker/node_modules/pcap/pcap.js:123:12)
error	Caught by controller[0]: at new PcapSession (/opt/iobroker/node_modules/pcap/pcap.js:49:39)
error	Caught by controller[0]: Error: socket: Operation not permitted
info	instance system.adapter.amazon-dash.0 started with pid 1094`

pi@helios:~ $ node -v
v8.16.0
pi@helios:~ $ npm -v
6.4.1

libpcap-dev is current version (1.8.1-3)  --> was not updated ?

re-installing the adapter (v. 0.3.1) does not bring any advantage...

Reviewing the logs of the last days, the previous node version was v8.15.1 .... with this version, everything was working well. (see upgraded packages, nodejs was one of the upgraded ones...)

Regards,
Matthias

**Comment by Acer54** [comment]
Update:
a `sudo setcap 'cap_net_raw,cap_net_admin+eip' $(readlink -f $(which node))` like suggested [here](https://www.blogging-it.com/node-pcap-module-error-socket-operation-not-permitted-fehler-wenn-pcapsession-geoeffnet-wird/programmierung/javascript/nodejs.html) fixed the permission issue.

Hope this is helpful for anyone with the same problem.
