### ISSUE TITLE
Adapter lässt sich nicht Starten

### ISSUE THREAD

**Issue by DerDoubleD** [PArns/ioBroker.amazon-dash#83]
Hallo
Ich habe an der Konfiguration eigentlich nichts geändert.
Leider startet der Adapter nicht mehr.
Logauszug:
```
2021-06-07 06:19:23.055 - error: amazon-dash.0 (15651) adapter disabled
2021-06-07 06:19:23.172 - warn: amazon-dash.0 (15651) Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason
2021-06-07 06:19:23.856 - error: host.iobrokerpi instance system.adapter.amazon-dash.0 terminated with code 3 (NO_ADAPTER_CONFIG_FOUND)
2021-06-07 06:19:23.857 - info: host.iobrokerpi Do not restart adapter system.adapter.amazon-dash.0 because disabled or deleted
2021-06-07 06:29:18.589 - info: host.iobrokerpi "system.adapter.amazon-dash.0" enabled
2021-06-07 06:29:18.685 - info: host.iobrokerpi instance system.adapter.amazon-dash.0 started with pid 16805
2021-06-07 06:29:20.472 - info: amazon-dash.0 (16805) starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.amazon-dash, node: v12.22.1, js-controller: 3.2.16
2021-06-07 06:29:20.507 - info: amazon-dash.0 (16805) starting pcap session on default interface
2021-06-07 06:29:20.512 - error: amazon-dash.0 (16805) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-06-07 06:29:20.512 - error: amazon-dash.0 (16805) unhandled promise rejection: socket: Operation not permitted
2021-06-07 06:29:20.515 - error: amazon-dash.0 (16805) Error: socket: Operation not permitted
at new PcapSession (/opt/iobroker/node_modules/pcap/pcap.js:60:39)
at Object.exports.createSession (/opt/iobroker/node_modules/pcap/pcap.js:131:12)
at main (/opt/iobroker/node_modules/iobroker.amazon-dash/main.js:90:29)
at Adapter. (/opt/iobroker/node_modules/iobroker.amazon-dash/main.js:53:9)
at Adapter.emit (events.js:314:20)
at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8479:34
2021-06-07 06:29:20.516 - error: amazon-dash.0 (16805) socket: Operation not permitted
2021-06-07 06:29:20.562 - info: amazon-dash.0 (16805) cleaned everything up...
2021-06-07 06:29:20.564 - info: amazon-dash.0 (16805) terminating
2021-06-07 06:29:20.565 - warn: amazon-dash.0 (16805) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-06-07 06:29:21.265 - error: host.iobrokerpi instance system.adapter.amazon-dash.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-06-07 06:29:21.266 - info: host.iobrokerpi Restart adapter system.adapter.amazon-dash.0 because enabled
2021-06-07 06:29:29.719 - info: host.iobrokerpi "system.adapter.amazon-dash.0" disabled
```

**Comment by Apollon77** [comment]
execute "iobroker fix"

**Comment by Apollon77** [comment]
permissions are broken and need to be re-set
